# Generated by Django 6.0.7 on 2026-08-04 19:43

import django.db.models.deletion
import django_edit_away.models
import pubs.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('label', models.CharField(max_length=200)),
                ('relator', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('bib_number', models.PositiveIntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('suffix', models.CharField(blank=True, max_length=50)),
                (
                    'election_date',
                    models.PositiveIntegerField(validators=[pubs.models.validate_year]),
                ),
                ('office', models.CharField(blank=True, max_length=100)),
                ('bio', django_edit_away.models.TiptapField()),
                ('bio_note', models.TextField(blank=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='images')),
                ('image_alt_text', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True)),
                (
                    'created_by',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('AM', 'Alex Mazzaferro'),
                            ('JA', 'Jeff Appelhans'),
                            ('EMJ', 'Unknown EMJ'),
                            ('AV', 'Unknown AV'),
                            ('JF', 'Julie Fisher'),
                            ('CP', 'Unknown CP'),
                            ('SB', 'Unknown SB'),
                            ('YS', 'Unknown YS'),
                            ('GS', 'Unknown GS'),
                            ('CF', 'Unknown CF'),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    'drupal_nid',
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('identifier', models.CharField(max_length=50)),
                ('editions_note', models.TextField(blank=True)),
                ('holding_note', django_edit_away.models.TiptapField()),
                ('title', models.TextField()),
                (
                    'year_published',
                    models.PositiveIntegerField(validators=[pubs.models.validate_year]),
                ),
                ('publication', models.CharField(max_length=255)),
                (
                    'record_source',
                    models.CharField(
                        choices=[
                            ('AAS', 'American Antiquarian Society'),
                            ('APS', 'American Philosophical Society'),
                            ('BNF', 'Bibliothèque nationale de France'),
                            ('CORN', 'Cornell Uniersity Library'),
                            ('ESTC', 'English Short Title Catalogue'),
                            ('FOUNDERS', 'Founders Online'),
                            ('HARV', 'Harvard Library'),
                            ('HSP', 'Historical Society of Pennsylvania'),
                            ('HUNT', 'The Huntington'),
                            ('JCB', 'John Carter Brown Library'),
                            ('LCP', 'Library Company of Philadelphia'),
                            ('LOC', 'Library of Congress'),
                            ('NBY', 'The Newberry'),
                            ('NLM', 'National Library of Medicine'),
                            ('NYHS', 'The New York Historical'),
                            ('NYPL', 'New York Public Library'),
                            ('PENN', 'University of Pennsylvania Libraries'),
                            ('PU', 'Princeton University Library'),
                            ('WC', 'Worldcat'),
                            ('YALE', 'Yale Library'),
                        ],
                        max_length=10,
                    ),
                ),
                ('references', models.CharField(blank=True, max_length=255)),
                ('aps_record_link', models.URLField(blank=True, null=True)),
                ('record_permalink', models.URLField()),
                (
                    'drupal_nid',
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                (
                    'annotator',
                    models.CharField(
                        choices=[
                            ('AM', 'Alex Mazzaferro'),
                            ('JA', 'Jeff Appelhans'),
                            ('EMJ', 'Unknown EMJ'),
                            ('AV', 'Unknown AV'),
                            ('JF', 'Julie Fisher'),
                            ('CP', 'Unknown CP'),
                            ('SB', 'Unknown SB'),
                            ('YS', 'Unknown YS'),
                            ('GS', 'Unknown GS'),
                            ('CF', 'Unknown CF'),
                        ],
                        max_length=3,
                    ),
                ),
                ('creators', models.ManyToManyField(to='pubs.creator')),
                ('members', models.ManyToManyField(to='pubs.member')),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('number_of_editions', models.PositiveIntegerField()),
                (
                    'year',
                    models.PositiveIntegerField(validators=[pubs.models.validate_year]),
                ),
                ('place_name', models.CharField(max_length=50)),
                (
                    'latitude',
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=8,
                        null=True,
                        validators=[pubs.models.verify_latlon],
                    ),
                ),
                (
                    'longitude',
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=8,
                        null=True,
                        validators=[pubs.models.verify_latlon],
                    ),
                ),
                (
                    'publication',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='pubs.publication',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('uri', models.CharField(blank=True, max_length=20, null=True)),
                ('heading', models.CharField(max_length=200)),
                (
                    'authority_source',
                    models.CharField(
                        choices=[
                            ('APS', 'American Philosophical Society'),
                            ('LOC', 'Library of Congress'),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    'coponents',
                    models.ManyToManyField(
                        blank=True, related_name='component_of', to='pubs.subject'
                    ),
                ),
            ],
            options={
                'ordering': ['heading'],
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='subjects',
            field=models.ManyToManyField(to='pubs.subject'),
        ),
        migrations.AddField(
            model_name='member',
            name='authority_record',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='pubs.subject'
            ),
        ),
        migrations.AddField(
            model_name='creator',
            name='subject',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='pubs.subject',
            ),
        ),
    ]
