# Generated by Django 6.1 on 2026-08-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pubs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subject",
            old_name="coponents",
            new_name="components",
        ),
        migrations.AddField(
            model_name="subject",
            name="drupal_tid",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="creator",
            name="relator",
            field=models.CharField(
                choices=[
                    ("RCP", "Addressee"),
                    ("ANN", "Annotator"),
                    ("ARR", "Arranger"),
                    ("ART", "Artist"),
                    ("ATT", "Attributed name"),
                    ("AUT", "Author"),
                    ("COM", "Compiler"),
                    ("CTB", "Contributor"),
                    ("EDT", "Editor"),
                    ("EGR", "Engraver"),
                    ("ILL", "Illustrator"),
                    ("LBT", "Librettist"),
                    ("TRL", "Translator"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="created_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AM", "Alex Mazzaferro"),
                    ("JA", "Jeff Appelhans"),
                    ("EMJ", "Unknown EMJ"),
                    ("AV", "Unknown AV"),
                    ("JF", "Julie Fisher"),
                    ("CP", "Unknown CP"),
                    ("SB", "Unknown SB"),
                    ("YS", "Yumi Shiroma"),
                    ("GS", "Unknown GS"),
                    ("CF", "Unknown CF"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="annotator",
            field=models.CharField(
                choices=[
                    ("AM", "Alex Mazzaferro"),
                    ("JA", "Jeff Appelhans"),
                    ("EMJ", "Unknown EMJ"),
                    ("AV", "Unknown AV"),
                    ("JF", "Julie Fisher"),
                    ("CP", "Unknown CP"),
                    ("SB", "Unknown SB"),
                    ("YS", "Yumi Shiroma"),
                    ("GS", "Unknown GS"),
                    ("CF", "Unknown CF"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="record_source",
            field=models.CharField(
                choices=[
                    ("AAS", "American Antiquarian Society"),
                    ("APS", "American Philosophical Society"),
                    ("BNF", "Bibliothèque nationale de France"),
                    ("CORN", "Cornell Uniersity Library"),
                    ("ESTC", "English Short Title Catalogue"),
                    ("FOUNDERS", "Founders Online"),
                    ("HARV", "Harvard Library"),
                    ("HSP", "Historical Society of Pennsylvania"),
                    ("HUNT", "The Huntington"),
                    ("JCB", "John Carter Brown Library"),
                    ("LCP", "Library Company of Philadelphia"),
                    ("LOC", "Library of Congress"),
                    ("NBY", "The Newberry"),
                    ("NLM", "National Library of Medicine"),
                    ("NYHS", "The New York Historical"),
                    ("NYPL", "New York Public Library"),
                    ("PENN", "University of Pennsylvania Libraries"),
                    ("PU", "Princeton University Library"),
                    ("WC", "Worldcat"),
                    ("YALE", "Yale Library"),
                    ("NONE", "None"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="authority_source",
            field=models.CharField(
                choices=[
                    ("APS", "American Philosophical Society"),
                    ("LOC", "Library of Congress"),
                    ("LCL", "Local"),
                ],
                max_length=3,
            ),
        ),
    ]
