# Generated by Django 6.1 on 2026-08-13 16:06

import django_edit_away.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pubs", "0002_rename_coponents_subject_components_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="bio",
            field=django_edit_away.models.TiptapField(blank=True, null=True),
        ),
    ]
