# Generated by Django 6.1 on 2026-08-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pubs", "0003_alter_member_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="bib_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
