# Generated by Django 6.1 on 2026-08-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pubs", "0004_alter_member_bib_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="bib_number",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
