# Generated by Django 6.1 on 2026-08-13 18:13

import django_edit_away.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pubs", "0005_alter_member_bib_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="holding_note",
            field=django_edit_away.models.TiptapField(blank=True, null=True),
        ),
    ]
