# Generated by Django 6.1 on 2026-08-13 18:22

import pubs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pubs", "0006_alter_publication_holding_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="year_published",
            field=models.PositiveIntegerField(
                blank=True, null=True, validators=[pubs.models.validate_year]
            ),
        ),
    ]
