# Generated by Django 6.1 on 2026-08-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pubs", "0007_alter_publication_year_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="record_source",
            field=models.CharField(
                choices=[
                    ("AAS", "American Antiquarian Society"),
                    ("APS", "American Philosophical Society"),
                    ("BNF", "Bibliothèque nationale de France"),
                    ("CORN", "Cornell University Library"),
                    ("ESTC", "English Short Title Catalogue"),
                    ("FOUNDERS", "Founders Online"),
                    ("HARV", "Harvard Library"),
                    ("HSP", "Historical Society of Pennsylvania"),
                    ("HUNT", "The Huntington"),
                    ("JCB", "John Carter Brown Library"),
                    ("LCP", "Library Company of Philadelphia"),
                    ("LOC", "Library of Congress"),
                    ("NBY", "The Newberry"),
                    ("NLM", "National Library of Medicine"),
                    ("NYHS", "The New York Historical"),
                    ("NYPL", "New York Public Library"),
                    ("PENN", "University of Pennsylvania Libraries"),
                    ("PU", "Princeton University Library"),
                    ("WC", "Worldcat"),
                    ("YALE", "Yale Library"),
                    ("NONE", "None"),
                ],
                max_length=10,
            ),
        ),
    ]
