# Generated by Django 6.1 on 2026-08-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pubs", "0008_alter_publication_record_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="images/"),
        ),
    ]
