# Generated by Django 6.1 on 2026-08-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pubs", "0009_alter_member_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="created_by",
            new_name="annotator",
        ),
        migrations.AlterField(
            model_name="creator",
            name="relator",
            field=models.CharField(
                choices=[
                    ("RCP", "Addressee"),
                    ("ANN", "Annotator"),
                    ("ARR", "Arranger"),
                    ("ART", "Artist"),
                    ("ATT", "Attributed name"),
                    ("AUT", "Author"),
                    ("COM", "Compiler"),
                    ("CTB", "Contributor"),
                    ("EDT", "Editor"),
                    ("EGR", "Engraver"),
                    ("ILL", "Illustrator"),
                    ("LBT", "Librettist"),
                    ("PRT", "Printer"),
                    ("TRL", "Translator"),
                ],
                max_length=3,
            ),
        ),
    ]
